service       : botleg

provider:
  environment : ${file(env.yml)}
  memorySize  : 256
  name        : aws
  region      : us-east-1
  runtime     : nodejs8.10
  timeout     : 60

package:
  exclude:
    - .git/**

functions:
  count:
    handler   : handlers/count.handler
    events:
    - http:
        path: count
        method: get
        cors: false

  comments:
    handler   : handlers/comments.handler
    events:
    - http:
        path: comments
        method: get
        cors: false
