service: botleg

provider:
  environment: ${file(env.yml)}
  memorySize: 256
  name: aws
  region: us-east-1
  runtime: nodejs8.10
  timeout: 60

package:
  exclude:
  - .git/**

functions:
  count:
    handler: handlers/count.handler
    events:
    - http:
        path: count
        method: get
        cors: false

  searchFirst:
    handler: handlers/search.single
    events:
    - http:
        path: search/{query}
        method: get
        cors:
          origin: https://botleg.com

  searchPaginated:
    handler: handlers/search.paginated
    events:
    - http:
        path: search/{query}/{page}
        method: get
        cors:
          origin: https://botleg.com

  commentsAll:
    handler: handlers/comments.all
    events:
    - http:
        path: comments
        method: get
        cors: false

  commentsPost:
    handler: handlers/comments.post
    events:
    - http:
        path: comments/{id}
        method: get
        cors:
          origin: https://botleg.com

  commentsWrite:
    handler: handlers/write.handler
    events:
    - http:
        path: comments/{id}
        method: post
        cors:
          origin: https://botleg.com

  commit:
    handler: handlers/commit.handler
    events:
    - http:
        path: commit
        method: post
        cors: false
